apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis-master
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: backend
  template:
    metadata: 
      name: redis-master-pod
      labels:
        app: backend
    spec:
      containers:
      - name: master-redis-datacenter
        image: redis
        resources:
          requests: 
            memory: 100Mi
            cpu: 100m
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
spec: 
  selector:
    app: backend
  ports:
  - port: 6379
    targetPort: 6379
